### ISSUE TITLE
...zpm:USER>install airplane...It's a typo ? or will it be done in the future?

### ISSUE THREAD

**Issue by SergeyMi37** [flnaves/airplane#1]
It's a typo ? or will it be done?
... from Read.me
Make sure you have git and Docker desktop installed.

How to Run the Application
Installation with ZPM
zpm:USER>install airplane
...

**Comment by flnaves** [comment]
Its a typo, i will finish until 28 February

Em sex., 26 de fev. de 2021 às 13:27, Sergey Mikhaylenko <
notifications@github.com> escreveu:
